// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.2
// source: table_meta.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TableMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Partitions       int64    `protobuf:"varint,1,opt,name=partitions,proto3" json:"partitions,omitempty"`
	TotalFields      int32    `protobuf:"varint,2,opt,name=total_fields,json=totalFields,proto3" json:"total_fields,omitempty"`
	PartitionKeyName string   `protobuf:"bytes,3,opt,name=partition_key_name,json=partitionKeyName,proto3" json:"partition_key_name,omitempty"`
	PartitionKeyType string   `protobuf:"bytes,4,opt,name=partition_key_type,json=partitionKeyType,proto3" json:"partition_key_type,omitempty"`
	SortKeyName      string   `protobuf:"bytes,5,opt,name=sort_key_name,json=sortKeyName,proto3" json:"sort_key_name,omitempty"`
	SortKeyType      string   `protobuf:"bytes,6,opt,name=sort_key_type,json=sortKeyType,proto3" json:"sort_key_type,omitempty"`
	OtherFieldsNames []string `protobuf:"bytes,7,rep,name=other_fields_names,json=otherFieldsNames,proto3" json:"other_fields_names,omitempty"`
	OtherFieldsTypes []string `protobuf:"bytes,8,rep,name=other_fields_types,json=otherFieldsTypes,proto3" json:"other_fields_types,omitempty"`
}

func (x *TableMeta) Reset() {
	*x = TableMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_table_meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableMeta) ProtoMessage() {}

func (x *TableMeta) ProtoReflect() protoreflect.Message {
	mi := &file_table_meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableMeta.ProtoReflect.Descriptor instead.
func (*TableMeta) Descriptor() ([]byte, []int) {
	return file_table_meta_proto_rawDescGZIP(), []int{0}
}

func (x *TableMeta) GetPartitions() int64 {
	if x != nil {
		return x.Partitions
	}
	return 0
}

func (x *TableMeta) GetTotalFields() int32 {
	if x != nil {
		return x.TotalFields
	}
	return 0
}

func (x *TableMeta) GetPartitionKeyName() string {
	if x != nil {
		return x.PartitionKeyName
	}
	return ""
}

func (x *TableMeta) GetPartitionKeyType() string {
	if x != nil {
		return x.PartitionKeyType
	}
	return ""
}

func (x *TableMeta) GetSortKeyName() string {
	if x != nil {
		return x.SortKeyName
	}
	return ""
}

func (x *TableMeta) GetSortKeyType() string {
	if x != nil {
		return x.SortKeyType
	}
	return ""
}

func (x *TableMeta) GetOtherFieldsNames() []string {
	if x != nil {
		return x.OtherFieldsNames
	}
	return nil
}

func (x *TableMeta) GetOtherFieldsTypes() []string {
	if x != nil {
		return x.OtherFieldsTypes
	}
	return nil
}

var File_table_meta_proto protoreflect.FileDescriptor

var file_table_meta_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xcf, 0x02, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6d, 0x65, 0x74,
	0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x12, 0x2c, 0x0a, 0x12, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x6b, 0x65, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x22, 0x0a, 0x0d, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x6f, 0x72, 0x74, 0x4b, 0x65, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x65, 0x79,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x6f, 0x72,
	0x74, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x6f, 0x74, 0x68, 0x65,
	0x72, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x12, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x10, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x54,
	0x79, 0x70, 0x65, 0x73, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_table_meta_proto_rawDescOnce sync.Once
	file_table_meta_proto_rawDescData = file_table_meta_proto_rawDesc
)

func file_table_meta_proto_rawDescGZIP() []byte {
	file_table_meta_proto_rawDescOnce.Do(func() {
		file_table_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_table_meta_proto_rawDescData)
	})
	return file_table_meta_proto_rawDescData
}

var file_table_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_table_meta_proto_goTypes = []interface{}{
	(*TableMeta)(nil), // 0: table_meta
}
var file_table_meta_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_table_meta_proto_init() }
func file_table_meta_proto_init() {
	if File_table_meta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_table_meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_table_meta_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_table_meta_proto_goTypes,
		DependencyIndexes: file_table_meta_proto_depIdxs,
		MessageInfos:      file_table_meta_proto_msgTypes,
	}.Build()
	File_table_meta_proto = out.File
	file_table_meta_proto_rawDesc = nil
	file_table_meta_proto_goTypes = nil
	file_table_meta_proto_depIdxs = nil
}
